### ISSUE TITLE
where is the pinout definition

### ISSUE THREAD

**Issue by cozmo14047** [playfultechnology/esp32-eyes#2]
HI @alastaira im trying to use this with a esp 32 cam board can you tell me where the pin definition code is 
many thanks

**Comment by alastaira** [comment]
Not many usable pins on an ESP32-CAM board: https://randomnerdtutorials.com/esp32-cam-ai-thinker-pinout/

**Comment by cozmo14047** [comment]
yes i 

> Not many usable pins on an ESP32-CAM board: https://randomnerdtutorials.com/esp32-cam-ai-thinker-pinout/

yes i know but i have got the screen working with the ssd1306 libary so i want to know where in the code you call the pins so i can change it
